### PR TITLE
Calculate go enrichment improvement

### PR DESCRIPTION
**Pull request by jpquast**
Adds a new argument to `calculate_go_enrichment()` and also fixes a bug with provided factor columns.

### CODE REVIEW

**Comment by elena-krismer** [comment]
when plotting the barplot the label_size is shown in the legend (which i guess shouldnt be there)

**Comment by elena-krismer** [comment]
Further I would consider to create the label name when creating the input data, so its accessible from the `data`property of the plot

```
paste0(
                .data$n_significant_proteins_in_process,
                "/",
                .data$n_detected_proteins_in_process,
                "(",
                round(.data$n_significant_proteins_in_process / .data$n_detected_proteins_in_process * 100, digits = 1),
                "%)"
              ),
```

This would allow to adjust the labels after plotting 
```
plot +  geom_text(aes(label = labels), size = 5)
```

**Review by elena-krismer — CHANGES_REQUESTED** [review]
looks good despite the label/pt in the barplot legend

**Comment by jpquast** [comment]
I think you might not have been in the newest commit since I had already fixed the legend issue. 
Thanks for the suggestion regarding adding the label to the data. It is now implemented.

**Review by elena-krismer — APPROVED** [review]

**Pull request merged**
